// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqppzlbmrlawjacyizei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcHB6bGJtcmxhd2phY3lpemVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjQ0MjIsImV4cCI6MjA3NDAwMDQyMn0.BDcxuAEgIRVew6Ozt2xV3m0f2FpkPaSu1nvkbe1Yi4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Helper function to get session ID from localStorage
const getSessionId = () => {
  return localStorage.getItem('business-goals-session') || '';
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-session-id': getSessionId(),
    },
  },
});